### ISSUE TITLE
Sort history descendingly

### ISSUE THREAD

**Issue by J4YB3** [J4YB3/discord-movie-night-bot#57]
## Description
_**As a**_  User
_**I want**_  to have the history sorted
_**so that**_ the latest watched movie appears first

On this occasion, also let the user jump directly to specific pages in the history

## Acceptance Criteria
- [ ] Jump directly to specific pages
- [x] History is sorted with latest at top

**Comment by JulianDroste** [comment]
User sorted is a little more tricky I would imagine. I currently have no preferred approach to solving that part of the issue.
